services:
  pykmip-server:
    build:
      context: pykmip-server
    ports:
      - 5696:5696
    volumes:
      - ./cert:/cert
  kmip-health-checker:
    build: https://github.com/FriedrichRezner/kmip-health-checker.git
    ports:
      - 3322:3322
    environment:
      - KMIP_SERVER_HOST=pykmip-server
      - KMIP_SERVER_PORT=5696
      - KMIP_SERVER_CIPHER_TYPE=49191
      - KMIP_SERVER_CERT_FILE=/cert/server.cert
      - KMIP_SERVER_KEY_FILE=/cert/server.key
    volumes:
      - ./cert:/cert